kind: Service
apiVersion: v1
metadata:
  name: ui-devportal
  namespace: openapi
spec:
  selector:
    app: ui-devportal
  ports:
  - name: http
    protocol: TCP
    nodePort: 32029
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: devportal-db
  namespace: openapi
spec:
  ports:
  - name: pgql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
